<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cal</string>
	</array>
	<key>name</key>
	<string>CAL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#namespace</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>action1</key>
		<dict>
			<key>begin</key>
			<string>\s*([a-zA-Z0-9_]+:)?\s*(action)\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.cal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)\s</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.name.action.cal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
			</array>
		</dict>
		<key>actor</key>
		<dict>
			<key>begin</key>
			<string>(actor)\s+(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.cal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)\s</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.name.actor.cal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#schedule</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#priority</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action1</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
			</array>
		</dict>
		<key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_if</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_foreach</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_while</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>block_foreach</key>
		<dict>
			<key>begin</key>
			<string>(foreach)[ ]+(.+)[ ]+(do)\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.cal</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)\s</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.foreach.cal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
			</array>
		</dict>
		<key>block_if</key>
		<dict>
			<key>begin</key>
			<string>(if)[ ]+(.+)[ ]+(then)\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.cal</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)\s</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.if.cal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
			</array>
		</dict>
		<key>block_while</key>
		<dict>
			<key>begin</key>
			<string>(while)[ ]+(.+)[ ]+(do)\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.cal</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)\s</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.while.cal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block_doc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
			</array>
		</dict>
		<key>comment_block</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.cal</string>
		</dict>
		<key>comment_block_doc</key>
		<dict>
			<key>begin</key>
			<string>/\*\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.cal</string>
		</dict>
		<key>comment_line</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.double-slash.cal</string>
		</dict>
		<key>decimal</key>
		<dict>
			<key>match</key>
			<string>[0-9\.]+</string>
			<key>name</key>
			<string>constant.numeric.decimal.cal</string>
		</dict>
		<key>function</key>
		<dict>
			<key>begin</key>
			<string>(function)[ ]+(.+):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.cal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.cal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)\s</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.name.function.cal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.other.cal</string>
				</dict>
			</array>
		</dict>
		<key>hex</key>
		<dict>
			<key>match</key>
			<string>0[x|X][0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric.hex.cal</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>match</key>
			<string>\bentities|structure|var\b</string>
			<key>name</key>
			<string>keyword.source.cal</string>
		</dict>
		<key>namespace</key>
		<dict>
			<key>begin</key>
			<string>(namespace)\s+(\w+)\s*:</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.cal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)\s?</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.name.namespace.cal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#network</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#actor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
			</array>
		</dict>
		<key>network</key>
		<dict>
			<key>begin</key>
			<string>(network)\s+(\w*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.cal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)\s</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.name.network.cal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct_line</string>
				</dict>
			</array>
		</dict>
		<key>prio_line</key>
		<dict>
		</dict>
		<key>priority</key>
		<dict>
			<key>begin</key>
			<string>(priority)\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)\s</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.name.priority.cal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prio_line</string>
				</dict>
			</array>
		</dict>
		<key>sched_line</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z0-9_]+)\s+\(([a-zA-Z0-9_]+)\)\s*(--&gt;)\s*([a-zA-Z0-9_]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.cal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.cal</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.other.cal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>keyword.control.sched_line.cal</string>
		</dict>
		<key>schedule</key>
		<dict>
			<key>begin</key>
			<string>(schedule)\s+(\w+)\s+(\w+)\s*:</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.cal</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.cal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)\s</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.cal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.name.schedule.cal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sched_line</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
		</dict>
		<key>struct_line</key>
		<dict>
			<key>begin</key>
			<string>((?:[a-zA-Z0-9_]+)\.)*([a-zA-Z0-9_]+)\s*(--&gt;)\s*((?:[a-zA-Z0-9_]+)\.)*([a-zA-Z0-9_]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.cal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.cal</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.cal</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.language.cal</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.character.cal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>keyword.control.struct_line.cal</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cal</string>
	<key>uuid</key>
	<string>0fdddb07-5be7-428e-8d5b-6ad101f904ab</string>
</dict>
</plist>
